# Generated by Django 5.0.6 on 2024-07-03 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Profile Photo')),
                ('university', models.CharField(blank=True, max_length=255, null=True, verbose_name='University')),
                ('degree', models.CharField(blank=True, max_length=100, null=True, verbose_name='Degree')),
                ('field_of_study', models.CharField(blank=True, max_length=100, null=True, verbose_name='Field of Study')),
                ('education_start_date', models.DateField(blank=True, null=True, verbose_name='Education Start Date')),
                ('education_end_date', models.DateField(blank=True, null=True, verbose_name='Education End Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('self_employed', 'Self-Employed'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('trainee', 'Trainee')], max_length=20, verbose_name='Employment Type')),
                ('location_type', models.CharField(choices=[('on_site', 'On-Site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=10, verbose_name='Location Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('role', models.CharField(max_length=100, verbose_name='Role')),
                ('skills', models.ManyToManyField(related_name='experiences', to='accounts.skill', verbose_name='Skills')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_experiences', to='accounts.userprofile')),
            ],
        ),
    ]
