# Generated by Django 5.0.6 on 2024-07-03 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='education_end_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='education_start_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='university',
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=255, verbose_name='University')),
                ('degree', models.CharField(max_length=100, verbose_name='Degree')),
                ('field_of_study', models.CharField(max_length=100, verbose_name='Field of Study')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='accounts.userprofile')),
            ],
        ),
    ]
