# Generated by Django 5.0.6 on 2024-07-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_resume_userprofile_skills'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('recruiter', 'job_title')},
        ),
    ]
