# Generated by Django 5.0.6 on 2024-07-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_job_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='about',
            field=models.CharField(blank=True, max_length=1000, verbose_name='About'),
        ),
    ]
