# Generated by Django 5.0.6 on 2024-07-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_userprofile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applications',
            field=models.JSONField(default=list),
        ),
    ]
