# Generated by Django 5.0.7 on 2024-07-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_job_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
    ]
