# Generated by Django 5.0.7 on 2024-07-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_job_skill_job_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='skills',
        ),
    ]
