# Generated by Django 5.0.7 on 2024-07-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_experience_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_location_type',
            field=models.CharField(choices=[('on_site', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], default='on_site', max_length=20, verbose_name='Job Location Type'),
        ),
    ]
